package com.laj.standardkotlinmvp.common

/**
 * Desc:
 * Author: hy
 * Date: 2019/7/18 10:39
 **/

const val FIRST_LOAD = 1
const val LOAD_MORE = 2
const val REFRESH = 3

const val COOKING_INFO_COMMENT_REPLY_CODE = 0x109
const val COOKING_INFO_COMMENT_PUBLISH_CODE = 0x1010
const val COOKING_INFO_COMMENT_THUMP_UP_CODE = 0x1011
const val COOKING_INFO_FAVORITE_CODE = 0x1014
const val COOKING_INFO_CANCEL_FAVORITE_CODE = 0x1015
const val COOKING_INFO_CANCEL_THUMP_UP_CODE = 0x1016
const val COOKING_INFO_COMMENT_CANCEL_THUMP_UP_CODE = 0x1017

const val QN_PAY_SUCCESS_MODULE_TYPE = 0x1020
const val QN_PAY_SUCCESS_MODULE_CODE = 0x1021